schema: "classroom50/repo-config/v1"
classroom: "aoc2026s2"
assignment: "registers-memory"
owner:
  username: "joao-ufscar3"
  id: 319255699
  accepted_at: "2026-08-27T13:28:20Z"
source:
  owner: "DC-UFSCar"
  owner_id: 11891488
  repo: "register-memory"
  branch: "main"
